### ISSUE TITLE
Undefined reference to core::panicking::panic

### ISSUE THREAD

**Issue by pgowda-cve** [rust-lang/compiler-builtins#476]
Hi,

We are trying to build mozjs-91 in debug mode on Yocto framework.

However, the build fails with the following error on compiler_builtins.

/libexec/i686-linux/gcc/i686-linux/12.1.0/ld: mozjs-91/91.8.0-r0/build/i686-linux/release/libjsrust.a(compiler_builtins-3fc4b4898efc1e1d.compiler_builtins.b3f4713f-cgu.3.rcgu.o): in function `compiler_builtins::int::specialized_div_rem::u64_div_rem':
compiler_builtins.b3f4713f-cgu.3:(.text._ZN17compiler_builtins3int19specialized_div_rem11u64_div_rem17ha9ef929772c35813E+0x178): undefined reference to `core::panicking::panic'

The issue is not seen when built without debug mode (DEBUG_BUILD = "1")
Tried to debug the issue and observed that building libstd-rs in release mode
fixed the issue.

The following issues were referred that are related to the same error
https://github.com/rust-lang/compiler-builtins/issues/347
https://github.com/rust-lang/compiler-builtins/issues/79

Tweaked the files to modify for
overflow-checks = false
opt-level = 1
However, it did not fix the issue.

**Comment by Amanieu** [comment]
Can you try with the latest nightly? According to https://github.com/rust-lang/rust/issues/96486#issuecomment-1180395751 it might have been fixed recently.

**Comment by pgowda-cve** [comment]
Thanks very much for the pointer.
Will check the issue with the latest sources as per your suggestion and try

**Comment by Yashinde145** [comment]
I checked the issue recently and it still exists with rust version 1.75 and 1.77.2 as well.

**Comment by Yashinde145** [comment]
Is there any commit that handles the issue?

Do we need to switch to rust nightly channel?

**Comment by Amanieu** [comment]
This was fixed by https://github.com/rust-lang/rust/pull/122580 and should be in 1.79.
